### ISSUE TITLE
Сделать попроще разрешение конфликтов при обновлении

### ISSUE THREAD

**Issue by aviskase** [nergal-perm/jira-stats#2]
Т.к. не все умеют работать с гит, то народу приходится заново клонить репозиторий при обновлении проги --- из-за того что config.json и report.html будут modified (а разрешать конфликты не умеют).

Для таких файлов обычно делают так:
1) в сам репозиторий добавить config-example.json и report-example.html
2) config.json и report.html добавить в .gitignore
3) в инструкции написать, что config-example.json и  report-example.html --- это примеры, и нужно создать свой config.json

после этого народ сможет просто делать git pull

**Comment by nergal-perm** [comment]
Поправил
